version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - PORT=3001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DOCKER_ENV=true
    volumes:
      - ./logs:/usr/src/app/logs
      - plugin-data:/usr/src/app/plugins
    restart: unless-stopped

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
  plugin-data: